name: 🐜 Bug Report
description: Report a reproducible bug in the Algorand Typescript language implementation.
title: '[Bug]: '
type: 'Bug'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Your input is invaluable in helping us improve Algorand Typescript.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug clearly and concisely.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide a step-by-step guide on how to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, please attach screenshots to help us understand the issue better.
    validations:
      required: false
  - type: input
    id: device-info
    attributes:
      label: Device Info
      description: Specify the device, OS, browser, and browser version you are using.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Context
      description: Add any other context about the bug you think would be helpful.
    validations:
      required: false
