name: Documentation Feedback
description: Provide feedback on our documentation.
title: '[Feedback]: '
type: 'Feedback'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to provide feedback on our documentation! Your input is invaluable in helping us improve.
  - type: input
    id: content-url

    attributes:
      label: Content URL
      description: Please provide the URL of the documentation page you are providing feedback on.
    validations:
      required: true
  - type: dropdown
    id: feedback-type
    attributes:
      label: Feedback Type
      description: What type of feedback do you have?
      multiple: true
      options:
        - Inaccuracy
        - Confusing explanation
        - Missing reference info
        - Code example needed
        - Other
      default: 0
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Please describe the problem you encountered in detail.
    validations:
      required: true
