name: ✨ Enhancement Request
description: Suggest an improvement or new feature for the Algorand Typescript language implementation.
title: '[Enhancement]: '
type: 'Feature'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing an enhancement! Share the problem, your suggested solution, and any supporting details so we can evaluate it quickly.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is the problem that we’re trying to solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Do you have a potential/suggested solution? Document more than one if possible.
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe the solution you’d like in detail.
    validations:
      required: true
  - type: textarea
    id: pros-cons
    attributes:
      label: Pros & Cons
      description: What are the advantages and disadvantages of this solution?
    validations:
      required: false
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Does the solution have any team or design dependencies?
    validations:
      required: false
