on:
  workflow_call:

jobs:
  ci-algo-ts:
    name: 'CI: algo-ts'
    uses: ./.github/workflows/node-ci.yml
    with:
      node-version: 20.x
      run-build: true
      audit-script: npm run audit
      working-directory: packages/algo-ts
      upload-artifact-name: algo-ts
      upload-artifact-path: ./packages/algo-ts/dist
  ci-puya-ts:
    name: 'CI: puya-ts'
    uses: ./.github/workflows/node-ci.yml
    needs:
      - ci-algo-ts
    with:
      download-artifact-pattern: algo-*
      download-artifact-path: ./packages-temp
      pre-run-script: mv packages-temp/algo-ts packages/algo-ts/dist
      node-version: 20.x
      run-build: true
      run-commit-lint: true
      build-script: npm run build
      audit-script: npm run audit
      upload-artifact-name: puya-ts
      upload-artifact-path: ./dist
