name: Prod Publish

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prod_release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate bot token
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_SK }}

      - uses: actions/checkout@v4
        with:
          # Fetch entire repository history so we can determine version number from it
          fetch-depth: 0
          token: ${{ steps.app_token.outputs.token }}

      - name: Set Git user as GitHub actions
        run: git config --global user.email "179917785+engineering-ci[bot]@users.noreply.github.com" && git config --global user.name "engineering-ci[bot]"

      - name: Merge main -> release
        uses: devmasx/merge-branch@6ec8363d74aad4f1615d1234ae1908b4185c4313
        with:
          type: now
          from_branch: main
          target_branch: release
          github_token: ${{ steps.app_token.outputs.token }}

      - name: Merge release -> main
        uses: devmasx/merge-branch@6ec8363d74aad4f1615d1234ae1908b4185c4313
        with:
          type: now
          from_branch: release
          target_branch: main
          message: Merge release back to main to get version increment [no ci]
          github_token: ${{ steps.app_token.outputs.token }}
