name: Publish

on:
  push:
    branches:
      - alpha
      - main
      - release
  workflow_dispatch:

concurrency: release

permissions:
  contents: write
  issues: write
  pull-requests: write
  checks: write

jobs:
  ci:
    name: Build and test
    uses: ./.github/workflows/ci-all.yml
    with:
      run-commit-lint: false

  release:
    name: Release
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - run: npm ci --ignore-scripts

      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate semantic version for @algorandfoundation/puya-ts
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish @algorandfoundation/algorand-typescript
        uses: JS-DevTools/npm-publish@v3
        id: publish-algo-ts
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: artifacts/algo-ts/package.json
          access: 'public'
          # Tagging 'main' branch with latest for now, even though it's beta because we don't have a non-beta
          tag: ${{ github.ref_name == 'alpha' && 'alpha' || github.ref_name == 'main' && 'latest' || github.ref_name == 'release' && 'latest' || 'pre-release' }}

      - name: Publish @algorandfoundation/puya-ts
        uses: JS-DevTools/npm-publish@v3
        id: publish-puya-ts
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: artifacts/puya-ts/package.json
          access: 'public'
          # Tagging 'main' branch with latest for now, even though it's beta because we don't have a non-beta
          tag: ${{ github.ref_name == 'alpha' && 'alpha' || github.ref_name == 'main' && 'latest' || github.ref_name == 'release' && 'latest' || 'pre-release' }}
