name: Publish

on:
  push:
    branches:
      - compiler-alpha
      - main
      - release
  workflow_dispatch:

concurrency: release

permissions:
  contents: write

jobs:
  ci:
    name: Build and test
    uses: ./.github/workflows/ci-all.yml

  release:
    name: Release
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: npm ci --ignore-scripts

      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish @algorandfoundation/algo-ts
        uses: JS-DevTools/npm-publish@v3
        id: publish-algo-ts
        with:
          token: ${{ secrets.NPM_SECRET }}
          package: artifacts/algo-ts/package.json
          access: 'public'
          dry-run: true

      - run: echo "type ${{ steps.publish-algo-ts.outputs.type }} name ${{ steps.publish-algo-ts.outputs.name }} version ${{ steps.publish-algo-ts.outputs.version }}"

      - name: Update puya-ts' peer dependency on algo-ts
        run: npx tsx ../../scripts/update-algo-ts-peer-dep.ts ${{ steps.publish-algo-ts.outputs.version }}
        working-directory: artifacts/puya-ts

      - name: Publish @algorandfoundation/puya-ts
        run: npx semantic-release

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_SECRET }}
